name: .NET Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet-version: ['8.x']
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # Восстанавливаем зависимости для основного проекта
      - name: Restore dependencies for main project
        run: dotnet restore D:/1LABS/BD/Lab_5/CityEvents/WebCityEvents

      # Восстанавливаем зависимости для тестового проекта
      - name: Restore dependencies for test project
        run: dotnet restore D:/1LABS/BD/Lab_5/CityEvents/WebCityEvents.Tests

      # Сборка основного проекта
      - name: Build main project
        run: dotnet build D:/1LABS/BD/Lab_5/CityEvents/WebCityEvents --no-restore

      # Сборка тестового проекта
      - name: Build test project
        run: dotnet build D:/1LABS/BD/Lab_5/CityEvents/WebCityEvents.Tests --no-restore

      # Запуск тестов
      - name: Test
        run: dotnet test D:/1LABS/BD/Lab_5/CityEvents/WebCityEvents.Tests --no-restore --verbosity normal
